[build]
builder = "NIXPACKS"
nixpacksPlan = {"providers":["...","python"]}
nixpacks = true

[deploy]
runtime = "V2"
python3Packages.uvicorn = "latest"
numReplicas = 1
startCommand = "python -m uvicorn server:app --host 0.0.0.0 --port 8000"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
